

INSERT INTO reference.acl_role (code,label,rec_st) VALUES ('ADMIN', 'Administrateur', 'C');
INSERT INTO reference.acl_role (code,label,rec_st) VALUES ('INSTITUTION', 'Etablissement', 'C');
INSERT INTO reference.acl_role (code,label,rec_st) VALUES ('USER', 'Utilisateur', 'C');
INSERT INTO reference.acl_role (code,label,rec_st) VALUES ('DRIVER', 'Conducteur', 'C');

insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('efce9a2a-cbc6-11e8-a9f2-02efb7513225','USER_MAIN_STATUS','ENABLED','Activé','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('efddab0a-cbc6-11e8-a9f3-02efb7513225','USER_MAIN_STATUS','DISABLED','Désactivé','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('efce9a2b-cbc6-11e8-a9f2-02efb7513225','USER_MAIN_TYPE','CLIENT','Client','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('efddab0b-cbc6-11e8-a9f3-02efb7513225','USER_MAIN_TYPE','INSTITUTION','Etablissement','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('efddab0c-cbc6-11e8-a9f3-02efb7513225','USER_MAIN_TYPE','ADMIN','Administrateur','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('efddab0d-cbc6-11e8-a9f3-02efb7513225','USER_MAIN_TYPE','DRIVER','Conducteur','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('038da470-cbc7-11e8-a9f4-02efb7513225','SITE_MAIN_TYPE','ENTITY','Entité','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('039c36f2-cbc7-11e8-a9f5-02efb7513225','SITE_MAIN_TYPE','INSTITUTION','Etablissement','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('039c36f3-cbc7-11e8-a9f5-02efb7513225','SITE_MAIN_TYPE','TRANSPORTER','Transporteur','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('0716a812-cbc7-11e8-a9f6-02efb7513225','SITE_POI_COUNTRY','FR','France','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('0d8d0d94-cbc7-11e8-a9f7-02efb7513225','HR_CONTACT_TYPE','MOBILE_PHONE','Téléphone portable','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('0d9b640c-cbc7-11e8-a9f8-02efb7513225','HR_CONTACT_TYPE','PHONE','Téléphone','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('0daaf444-cbc7-11e8-a9f9-02efb7513225','HR_CONTACT_TYPE','EMAIL','Email','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f88cba04-cbc9-11e8-a9fa-02efb7513225','SITE_MAIN_STATUS','ENABLED','Activé','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f89d5012-cbc9-11e8-a9fb-02efb7513225','SITE_MAIN_STATUS','DISABLED','Désactivé','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f2e30322-cbd5-11e8-9205-02efb7513225','HR_MAIN_GENDER','F','Femme','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f2f27b0e-cbd5-11e8-9206-02efb7513225','HR_MAIN_GENDER','H','Homme','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('58e68176-cbd6-11e8-9207-02efb7513225','HR_MAIN_STATUS','ENABLED','Activé','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('58f94428-cbd6-11e8-9208-02efb7513225','HR_MAIN_STATUS','DISABLED','Désactivé','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('a0b5f9e2-cc61-11e8-90f7-02efb7513225','HR_MAIN_TYPE','USER','Usager','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('a0b5f9a2-cc81-11e8-90f7-02efb7513225','HR_MAIN_TYPE','DRIVER','Conducteur','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('7698b882-cc6d-11e8-90f8-02efb7513225','HR_MAINSITE_TYPE','HOME','Maison','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('76d416ca-cc6d-11e8-90f9-02efb7513225','HR_MAINSITE_TYPE','INSTITUTION','Etablissement','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('76d416ca-cc6d-11e4-90f9-02efb7513225','HR_MAINSITE_TYPE','TRANSPORTER','Transporteur','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('0436ceae-cc6e-11e8-90fa-02efb7513225','SITE_MAIN_TYPE','HOME','Maison','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('de5a6dca-cdf4-11e8-9ab4-02efb7513225','VEHICLE_CAPACITY_UNIT','CHILD','Enfant','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('de9aa520-cdf4-11e8-9ab5-02efb7513225','VEHICLE_CAPACITY_TRANSPORTED','MARCHANT','Marchant','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('ded39010-cdf4-11e8-9ab6-02efb7513225','VEHICLE_CAPACITY_TRANSPORTED','FAUTEUIL','Fauteuil roulant','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('b03e79fe-ce03-11e8-9ab7-02efb7513225','VEHICLE_MAIN_STATUS','ENABLED','Activé','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('b051fa42-ce03-11e8-9ab8-02efb7513225','VEHICLE_MAIN_STATUS','DISABLED','Désactivé','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f041ba72-d6da-11e8-96f7-02efb7513225','HR_MAIN_TRANSPORTMODE','MARCHANT','Marchant','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f0591ffa-d6da-11e8-96f8-02efb7513225','HR_MAIN_TRANSPORTMODE','FAUTEUIL','Fauteuil roulant','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f0591ffb-d6da-11e8-96f8-02efb7513225','SCENARIO_MAIN_STATUS','DEFAULT','Non défini','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f0592000-d6da-11e8-96f8-02efb7513225','SCENARIO_MAIN_STATUS','OPERATION','Exploitation','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f0592001-d6da-11e8-96f8-02efb7513225','SCENARIO_MAIN_STATUS','PROJECT','Projet','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f0592002-d6da-11e8-96f8-02efb7513225','SCENARIO_MAIN_STATUS','ARCHIVE','Archivé','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f0591ffc-d6da-11e8-96f8-02efb7513225','OPTIM_MAIN_STATUS','RUNNING','En cours','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f0591ffd-d6da-11e8-96f8-02efb7513225','OPTIM_MAIN_STATUS','LOST','Perdu','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f0591ffe-d6da-11e8-96f8-02efb7513225','OPTIM_MAIN_STATUS','PAUSED','En pause','C');
insert into reference.util_thesaurus (id, cat, code, label, rec_st) values ('f0591fff-d6da-11e8-96f8-02efb7513225','OPTIM_MAIN_STATUS','FINISHED','Terminé','C');
insert into reference.util_thesaurus ( cat, code, label, rec_st) values ('OPTIM_MAIN_STATUS','WAITING','En attente','C');

insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('747769be-d860-11e8-b443-02efb7513225','TIMESLOT','MONDAY_AM','Lundi aller',1, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('748abe4c-d860-11e8-b444-02efb7513225','TIMESLOT','MONDAY_PM','Lundi retour',2, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('749c8d48-d860-11e8-b445-02efb7513225','TIMESLOT','TUESDAY_AM','Mardi aller',3, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('74ac3608-d860-11e8-b446-02efb7513225','TIMESLOT','TUESDAY_PM','Mardi retour',4, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('74cb943a-d860-11e8-b447-02efb7513225','TIMESLOT','WEDNESDAY_AM','Mercredi aller',5, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('74dc07a2-d860-11e8-b448-02efb7513225','TIMESLOT','WEDNESDAY_PM','Mercredi retour',6, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('74ebd466-d860-11e8-b449-02efb7513225','TIMESLOT','THURSDAY_AM','Jeudi aller',7, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('74fb96f8-d860-11e8-b44a-02efb7513225','TIMESLOT','THURSDAY_PM','Jeudi retour',8, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('750aee32-d860-11e8-b44b-02efb7513225','TIMESLOT','FRIDAY_AM','Vendredi aller',9, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('751c5cd0-d860-11e8-b44c-02efb7513225','TIMESLOT','FRIDAY_PM','Vendredi retour',10, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('750aee33-d860-11e8-b44b-02efb7513225','TIMESLOT','SATURDAY_AM','Samedi aller',11, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('751c5cd1-d860-11e8-b44c-02efb7513225','TIMESLOT','SATURDAY_PM','Samedi retour',12, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('750aee34-d860-11e8-b44b-02efb7513225','TIMESLOT','SUNDAY_AM','Dimanche aller',13, 'C');
insert into reference.util_thesaurus (id, cat, code, label, orderdisplay, rec_st) values ('751c5cd2-d860-11e8-b44c-02efb7513225','TIMESLOT','SUNDAY_PM','Dimanche retour',14, 'C');

INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/aclaction/has-access/{userId}/{actionCode}','Contrôler un droit','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/aclaction/list','Lister les actions','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/aclrole/list','Lister les rôles','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/aclrole/{id}','Afficher un rôle','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/aclrole/save','Enregistrer un rôle','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/aclrole/delete','Supprimer définitivement un rôle','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/aoi/list','Lister des AOIs','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/aoi/{AOIId}','Afficher une AOI','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/calendar/list','Liste des éléments du calendrier des demandes','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/calendar/to-timestamp','Convertir une date en timestamp','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/calendar/update','Mettre à jour le calendrier pour un scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/demand/list','Lister des demandes de transport','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/demand/{demandId}','Afficher une demande de transport','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/demand/save','Enregistrer une demande de transport','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/demand/mark-as-removed','Supprimer une demande de transport','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/demand/delete','Supprimer définitivement une demande de transport','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/group/list','Lister des groupes de demandes','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/group/{groupId}','Afficher un groupe de demandes','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/group/save','Enregistrer un groupe de demandes','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/group/mark-as-removed','Supprimer un groupe de demandes','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/group/delete','Supprimer définitivement une group de demandes','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/home/data/hrs','Accès au bouton Data/Usagers','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/home/data/hr','Accès aux boutons Data/Usager','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/home/logistics/demands','Accès au bouton Logistics/Demands','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/home/logistics/trip','Accès au bouton Logitics/Tournées','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/hr/list','Lister des usagers','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/hr/{hrId}','Afficher un usager','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/hr/routes','Lister les tournées affectées à un chauffeur','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/hr/save','Enregistrer un usager','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/hr/mark-as-removed','Supprimer un usager','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/hr/delete','Supprimer définitivement un usager','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/hr/update-durations','Changer les durées de montée et de descente d''usagers','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/import/csv','Importer des données depuis un fichier CSV','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/map/access-token','Récupérer la clé Mapbox','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/data','Accès au menu Data','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/data/institutions','Accès au menu Data/Etablissements','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/data/transporters','Accès au menu Data/Transporteurs','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/data/hrs','Accès au menu Data/Usagers','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/data/hr-drivers','Accès au menu Data/Conducteurs','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/data/vehicle-categories','Accès au menu Data/Catégories de véhicules','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/data/users','Accès au menu Data/Utilisateurs','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/data/acl','Accès au menu Data/Droits d''accès','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/data/import','Accès au menu Data/Import','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/logistics','Accès au menu Logitics','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/logistics/scenario','Accès au menu Logitics/Scénarios','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/logistics/trip','Accès au menu Logitics/Tournées','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/logistics/demands','Accès au menu Logitics/Demandes de transport','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/logistics/groups','Accès au menu Logitics/Groupes de demandes','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/optim','Accès au menu Optim','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/menu/optim/list','Accès au menu Optim/Optimisation','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/list','Lister des optimisations','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/default-params','Obtenir les paramètres d''optimisation par défaut','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/{id}','Afficher une optimisation','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/save','Enregistrer une optimisation','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/check','Vérifier la progression d''une optimisation','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/from-routes','Créer une instance à partir de routes existantes','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/from-scenario','Créer une instance à partir d''un scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/stop','Arrêter une optimisation sur le serveur d''optimisation','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/pause','Mettre en pause ou réveiller une optimisation','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/process-fifo','Demander le traitement de la file d''attente optimisation','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/optim/to-routes/{optimId}','Créer des routes à partir d''une instance','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/poi/list','Lister des POIs','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/poi/{POIId}','Afficher un POI','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/poi/list/transport','Lister des POIs associés à des usagers','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/poi/reverse-geocode','Calculer une adresse de POI','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/poi/save-acceptable-durations','Enregistrer des durées de trajet acceptables','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/poi/update-service-duration','Changer le temps de service du POI','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/poi/update-acceptable-durations','Demander la mise à jour de durées de trajet acceptables','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/poi/acceptable-durations','Calculer des durées de trajet acceptables','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/calendar','Obtenir un calendrier des tournées','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/insert-location','Insérer des données de localisation issues de véhicules réalisant les tournées','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/list','Lister des tournées','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/poi/list','Lister des POIs pour créer des routes','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/directions/{coordinates}','Calculer un itinéraire','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/save','Enregistrer une tournée','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/mark-as-removed','Supprimer une tournée','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/delete','Supprimer définitivement une tournée','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/restore','Restaurer des tournées à partir d''une instance d''optimisation','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/start','Notifier le début d''une tournée','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/end','Notifier la fin d''une tournée','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/route/visit','Notifier la visite d''un point d''une tournée','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/list','Lister des scénarios','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/minimap/{scenarioId}','Localiser les routes du scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/{scenarioId}','Afficher un scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/save','Enregistrer un scenario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/duplicate','Dupliquer un scenario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/duplicate-route','Dupliquer une route vers un scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/mark-as-removed','Supprimer un scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/delete','Supprimer définitivement un scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/calendar/copy','Propager des tournées dans le calendrier d''un scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/poi/list','Lister les POIs dans un scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/scenario/route/list','Lister les tournées dans un scénario','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/site/list','Lister des sites','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/site/{siteId}','Afficher un site','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/site/save','Enregistrer un site','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/site/mark-as-removed','Supprimer un site','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/site/delete','Supprimer définitivement un site','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/thesaurus/list','Lister des valeurs de thesaurus','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/thesaurus/is-morning/{thesaurusId}','Savoir si une entrée du thesaurus correspond à un aller','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/thesaurus/{thesaurusId}','Obtenir une valeur de thesaurus','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/user/list','Lister des utilisateurs','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/user/{id}','Afficher un utilisateur','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/user/save','Enregistrer un utilisateur','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/user/update-password','Modifier un mot de passe','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/user/mark-as-removed','Supprimer un utilisateur','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/user/delete','Supprimer définitivement un utilisateur','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/vehiclecategory/list','Lister des catégories de véhicules','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/vehiclecategory/{id}','Afficher une catégorie de véhicules','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/vehiclecategory/save','Enregistrer une catégorie de véhicules','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/vehiclecategory/mark-as-removed','Supprimer une catégorie de véhicules','C');
INSERT INTO reference.acl_action (code,label,rec_st) VALUES ('/vehiclecategory/delete','Supprimer définitivement une catégorie de véhicules','C');
